name: ScoreboardScreen
main: io.github.scoreboardscreen.main.ScoreboardScreen
version: 2.0.0
depend: [PlaceholderAPI, RapidFramework]
commands:
  scoreboardscreen:
    description: blah
    aliases: [ss]