name: ScoreboardScreen
main: io.github.wysohn.scoreboardscreen.main.ScoreboardScreen
version: 3.2.7
depend: [
  ]
commands:
  scoreboardscreen:
    aliases:
    - sco
    - sboard
    description: description
author: wysohn
authors: [
  ]
softdepend:
- RapidFramework
- Vault
- PlaceholderAPI
permissions:
  scoreboardscreen:
    description: root permission
api-version: '1.13'
